
sheetIndex=0

########## Reference Info ##########
analyte_groups_by_testno = {
    "SW6020": "Soil Metals",
    "SW7199": "Soil Metals",
    "435 CARB": "Soil Metals",
    "SW8015B": "Soil TPHs, BTEX & Organic",
    "SW8021B/8015Bm": "Soil TPHs, BTEX & Organic",
    "G-MBTEX_E": "Soil TPHs, BTEX & Organic",
    "SW8315A": "Soil TPHs, BTEX & Organic",
    "SW8260B": "VOCs",
    "SW8270C": "SVOCs",
    "SW8081A/8082": "Soil Pesticides and PCBs",
    "SW8081B/8082A": "Soil Pesticides and PCBs",
    "SW8082": "Soil Pesticides and PCBs",
    "SW8081A": "Soil Pesticides and PCBs",
    "SW9045C": "Other Inorganic",
    "SWchpt7_CN": "Other Inorganic",
    "SWchpt7_S": "Other Inorganic",
    "SM4500-CN¯ CE": "Other Inorganic",
    "E1030": "Other Inorganic",
    "ASTM D2216-05": "Other Inorganic",
    "SW9045C_Corr" : "Other Inorganic",
    "SW8000": "Other Inorganic",
    "DOD QSM":"PFAS",
    "SW9045D":"Other Inorganic"
}

GW_analyte_groups_by_testno = {
    "435 CARB": "GW Metals",
    "E200.8": "GW Metals",
    "SW8015B": "GW TPHs, BTEX & Organic",
    "SW8021B/8015Bm": "GW TPHs, BTEX & Organic",
    "G-MBTEX_E": "GW TPHs, BTEX & Organic",
    "E418.1": "GW TPHs, BTEX & Organic",
    "SW8260B": "GW VOCs",
    "SW8270C": "GW SVOCs",
    "SW8081A/8082": "GW Pesticides and PCBs",
    "SW8081B/8082A": "GW Pesticides and PCBs",
    "SW8082": "GW Pesticides and PCBs",
    "SW8081A": "GW Pesticides and PCBs",
    "SW9045C": "GW Other Inorganics",
    "SWchpt7_CN": "GW Other Inorganics",
    "SWchpt7_S": "GW Other Inorganics",
    "Kelada-01": "GW Other Inorganics",
    "SM4500-CN¯ CE": "GW Other Inorganics",
    "E1030": "GW Other Inorganics",
    "SM2540 D-1997": "GW Other Inorganics",
    "SM5220 D-1997": "GW Other Inorganics",
    "SM2510Bm-1997": "GW Other Inorganics",
    "E300.1": "GW Other Inorganics",
    "SW9045C_Corr" : "GW Other Inorganics",
    "SM4500-S¯² B": "GW Other Inorganics",
    "SM4500H+B": "GW Other Inorganics",
    "TO15" : "Soil Vapor VOCs",
    "ASTM D 1946-90" : "Soil Vapor VOCs",
 }


table1_groups_by_testno = {
    "G-MBTEX_E": "TPHs-G/BTEX/MTBE",
    "SW8021B/8015Bm": "TPHs-G/BTEX/MTBE",
    "SW8015B": "TPHs-D/MO",
    "SW8315A": "Carbonyls",
    "SW8260B": "VOCs",
    "TO15" : "VOCs", #Soil Vapor
    "SW8270C": "SVOCs",
    "SW6020": "Title-22 Metals",
    "SW7199": "Title-22 Metals",
    "E200.8": "Title-22 Metals",
    "7199_TTLC_LL_S": "Cr +6",
    "SW8081A/8082": "Pesticides and PCBs",
    "SW8081B/8082A": "Pesticides and PCBs",
    "SW8082": "Pesticides and PCBs",
    "SW8081A": "Pesticides and PCBs",
    "SWchpt7_CN": "Reactive CN-",
    "SM4500-CN¯ CE": "CN-",
    "Kelada-01": "CN-",
    "SW9045C": "pH",
    "SM4500H+B": "pH",
    "ASTM D 1946-90" : "Methane",
    "E1030": "RCI",
    "SWchpt7_S": "Sulfides",
    "SM2540 D-1997": "TSS",
    "SM5220 D-1997": "COD",
    "E418.1": "TRPH",
    "SM2510Bm-1997": "Salinity",
    "E300.1": "Cl",
    "SM4500-S¯² B": "Diss. Sulfides",
    "435 CARB": "Asbestos",
    "SW8000" : "Soil Moisture Content", 
    "DOD QSM":"PFAS",
    "SW9045C_Corr" : "Corrosivity",
    "SW9045D":"pH"

}
analyte_name_to_display_name = {
    #Metals
    "Antimony": "Sb",
    "WET Antimony": "WET Sb",
    "Arsenic": "As",
    "WET Arsenic": "WET As",
    "TCLP Arsenic": "TCLP As",
    "Barium": "Ba",
    "WET Barium": "WET Ba",
    "TCLP Barium": "TCLP Ba",
    "Beryllium": "Be",
    "WET Beryllium": "WET Be",
    "Cadmium": "Cd",
    "WET Cadmium": "WET Cd",
    "TCLP Cadmium": "TCLP Cd",
    "Chromium": "Cr",
    "WET Chromium": "WET Cr",
    "TCLP Chromium": "TCLP Cr",
    "Hexavalent chromium": "Cr +6",
    "WET Hexavalent chromium": "WET Cr+6",
    "Cobalt": "Co",
    "WET Cobalt": "WET Co",
    "Copper": "Cu",
    "WET Copper": "WET Cu",
    "Lead": "Pb",
    "WET Lead": "WET Pb",
    "TCLP Lead": "TCLP Pb",
    "Mercury": "Hg",
    "WET Mercury": "WET Hg",
    "TCLP Mercury": "TCLP Hg",
    "Molybdenum": "Mo",
    "WET Molybdenum": "WET Mo",
    "Nickel": "Ni",
    "WET Nickel": "WET Ni",
    "Selenium": "Se",
    "WET Selenium": "WET Se",
    "TCLP Selenium": "TCLP Se",
    "Silver": "Ag",
    "WET Silver": "WET Ag",
    "TCLP Silver": "TCLP Ag",
    "Thallium": "Tl",
    "WET Thallium": "WET Tl",
    "Vanadium": "V",
    "WET Vanadium": "WET V",
    "Zinc": "Zn",
    "WET Zinc": "WET Zn",
    "Asbestos":"Asbestos",
    #TPHs/BETX
    "TPH(g)": "TPHs-G",
    "TPH(g) (C6-C12)": "TPHs-G",
    "TPH-Diesel (C10-C23)": "TPHs-D",
    "TPH-Motor Oil (C18-C36)": "TPHs-MO",
    "Benzene":"Benzene",
    "Ethyl Benzene":"Ethyl Benzene",
    "Ethylbenzene":"Ethyl Benzene",
    "Toluene":"Toluene",
    "TRPH":"TRPH",
    "Xylenes":"Xylenes",
    "MTBE":"MTBE",
    "Carbonyls":"Carbonyls",
    "Xylenes, Total" : "Total Xylenes",
    #VOCs
    "Acetone" : "Acetone",
    "tert-Amyl methyl ether (TAME)":"TAME",
    "Benzene":"Benzene",
    "Bromobenzene":"Bromobenzene",
    "Bromochloromethane":"Bromochloromethane",
    "Bromodichloromethane":"Bromodichloromethane",
    "Bromoform":"Bromoform",
    "Bromomethane":"Bromomethane",
    "2-Butanone (MEK)" :"2-Butanone",
    "t-Butyl alcohol (TBA)":"TBA",
    "n-Butyl benzene":"n-Butyl benzene",
    "sec-Butyl benzene":"sec-Butyl benzene",
    "tert-Butyl benzene":"tert-Butyl benzene",
    "Carbon Disulfide":"Carbon Disulfide",
    "Carbon Tetrachloride":"Carbon Tetrachloride",
    "Chlorobenzene":"Chlorobenzene",
    "Chloroethane" : "Chloroethane",
    "Chloroform" : "Chloroform",
    "Chloromethane" : "Chloromethane",
    "2-Chlorotoluene" : "2-Chlorotoluene",
    "4-Chlorotoluene" : "4-Chlorotoluene",
    "Dibromochloromethane" : "Dibromochloromethane",
    "1,2-Dibromo-3-chloropropane" : "1,2-Dibromo-3-chloropropane",
    "1,2-Dibromoethane (EDB)" : "EDB",
    "Dibromomethane" : "Dibromomethane",
    "Dichlorodifluoromethane" : "Dichlorodifluoromethane",
    "1,2-Dichlorobenzene" : "1,2-Dichlorobenzene",
    "1,3-Dichlorobenzene" : "1,3-Dichlorobenzene",
    "1,4-Dichlorobenzene" : "1,4-Dichlorobenzene",
    "Dibromofluoromethane" : "Dibromofluoromethane",
    "1,1-Dichloroethane" : "1,1-Dichloroethane",
    "1,2-Dichloroethane (1,2-DCA)" : "1,2-DCA",
    "1,1-Dichloroethene" : "1,1-Dichloroethene",
    "cis-1,2-Dichloroethene" : "cis-1,2-Dichloroethene",
    "trans-1,2-Dichloroethene" : "trans-1,2-Dichloroethene",
    "1,2-Dichloropropane" : "1,2-Dichloropropane",
    "1,3-Dichloropropane" : "1,3-Dichloropropane",
    "1,3-Dichloropropene, Total" : "1,3-Dichloropropene, Total",
    "2,2-Dichloropropane" : "2,2-Dichloropropane",
    "1,1-Dichloropropene" : "1,1-Dichloropropene",
    "cis-1,3-Dichloropropene" : "cis-1,3-Dichloropropene",
    "trans-1,3-Dichloropropene" : "trans-1,3-Dichloropropene",
    "Diisopropyl ether (DIPE)" : "DIPE",
    "Ethylbenzene" : "Ethylbenzene",
    "Ethyl tert-butyl ether (ETBE)" : "ETBE",
    "Freon 113" : "Freon 113",
    "Hexachlorobutadiene" : "Hexachlorobutadiene",
    "Hexachloroethane" : "Hexachloroethane",
    "2-Hexanone" : "2-Hexanone",
    "Isopropylbenzene" : "Isopropylbenzene",
    "4-Isopropyl toluene" : "4-Isopropyl toluene",
    "Methyl-t-butyl ether (MTBE)" : "MTBE",
    "Methylene chloride" : "Methylene chloride",
    "4-Methyl-2-pentanone (MIBK)" : "MIBK",
    "Naphthalene" : "Naphthalene",
    "n-Propyl benzene" : "n-Propyl benzene",
    "Styrene" : "Styrene",
    "1,1,1,2-Tetrachloroethane" : "1,1,1,2-Tetrachloroethane",
    "1,1,2,2-Tetrachloroethane" : "1,1,2,2-Tetrachloroethane",
    "Tetrachloroethene" : "PCE",
    "Toluene" : "Toluene",
    "1,2,3-Trichlorobenzene" : "1,2,3-Trichlorobenzene",
    "1,2,4-Trichlorobenzene" : "1,2,4-Trichlorobenzene",
    "1,1,1-Trichloroethane" : "1,1,1-Trichloroethane",
    "1,1,2-Trichloroethane" : "1,1,2-Trichloroethane",
    "Trichloroethene" : "TCE",
    "Trichlorofluoromethane" : "Trichlorofluoromethane",
    "1,2,3-Trichloropropane" : "1,2,3-Trichloropropane",
    "1,2,4-Trimethylbenzene" : "1,2,4-Trimethylbenzene",
    "1,3,5-Trimethylbenzene" : "1,3,5-Trimethylbenzene",
    "Vinyl Chloride" : "Vinyl Chloride",
    "Total Xylenes" : "Total Xylenes",
    "Other VOCs" : "Other VOCs",

    
    #SVOCS
    "Acenaphthene" : "Acenaphthene",
    "Acenaphthylene" : "Acenaphthylene",
    "Acetochlor" : "Acetochlor",
    "Anthracene" : "Anthracene",
    "Benzidine" : "Benzidine",
    "Benzo (a) anthracene" : "Benzo (a) anthracene",
    "Benzo (b) fluoranthene" : "Benzo (b) fluoranthene",
    "Benzo (k) fluoranthene" : "Benzo (k) fluoranthene",
    "Benzo (g,h,i) perylene" : "Benzo (g,h,i) perylene",
    "Benzo (a) pyrene" : "Benzo (a) pyrene",
    "Benzyl Alcohol" : "Benzyl Alcohol",
    "1,1-Biphenyl" : "1,1-Biphenyl",
    "Bis (2-ethylhexyl) Adipate" : "Bis (2-ethylhexyl) Adipate",
    "Bis (2-chloroethoxy) Methane" : "Bis (2-chloroethoxy) Methane",
    "Bis (2-chloroethyl) Ether" : "Bis (2-chloroethyl) Ether",
    "Bis (2-chloroisopropyl) Ether" : "Bis (2-chloroisopropyl) Ether",
    "Bis (2-ethylhexyl) Phthalate" : "Bis (2-ethylhexyl) Phthalate",
    "4-Bromophenyl Phenyl Ether" : "4-Bromophenyl Phenyl Ether",
    "Butylbenzyl Phthalate" : "Butylbenzyl Phthalate",
    "4-Chloroaniline" : "4-Chloroaniline",
    "4-Chloro-3-methylphenol" : "4-Chloro-3-methylphenol",
    "2-Chloronaphthalene" : "2-Chloronaphthalene",
    "2-Chlorophenol" : "2-Chlorophenol",
    "4-Chlorophenyl Phenyl Ether" : "4-Chlorophenyl Phenyl Ether",
    "Chrysene" : "Chrysene",
    "Dibenzo (a,h) anthracene" : "Dibenzo (a,h) anthracene",
    "Dibenzofuran" : "Dibenzofuran",
    "Di-n-butyl Phthalate" : "Di-n-butyl Phthalate",
    "1,2-Dichlorobenzene" : "1,2-Dichlorobenzene",
    "1,3-Dichlorobenzene" : "1,3-Dichlorobenzene",
    "1,4-Dichlorobenzene" : "1,4-Dichlorobenzene",
    "3,3-Dichlorobenzidine" : "3,3-Dichlorobenzidine",
    "2,4-Dichlorophenol" : "2,4-Dichlorophenol",
    "Diethyl Phthalate" : "Diethyl Phthalate",
    "2,4-Dimethylphenol" : "2,4-Dimethylphenol",
    "Dimethyl Phthalate" : "Dimethyl Phthalate",
    "4,6-Dinitro-2-methylphenol" : "4,6-Dinitro-2-methylphenol",
    "2,4-Dinitrophenol" : "2,4-Dinitrophenol",
    "2,4-Dinitrotoluene" : "2,4-Dinitrotoluene",
    "2,6-Dinitrotoluene" : "2,6-Dinitrotoluene",
    "Di-n-octyl Phthalate" : "Di-n-octyl Phthalate",
    "1,2-Diphenylhydrazine" : "1,2-Diphenylhydrazine",
    "Fluoranthene" : "Fluoranthene",
    "Fluorene" : "Fluorene",
    "Hexachlorobenzene" : "Hexachlorobenzene",
    "Hexachlorobutadiene" : "Hexachlorobutadiene",
    "Hexachlorocyclopentadiene" : "Hexachlorocyclopentadiene",
    "Hexachloroethane" : "Hexachloroethane",
    "Indeno (1,2,3-cd) pyrene" : "Indeno (1,2,3-cd) pyrene",
    "Isophorone" : "Isophorone",
    "2-Methylnaphthalene" : "2-Methylnaphthalene",
    "2-Methylphenol (o-Cresol)" : "2-Methylphenol (o-Cresol)",
    "3 & 4-Methylphenol (mp-Cresol)" : "3 & 4-Methylphenol (mp-Cresol)",
    "Naphthalene" : "Naphthalene",
    "2-Nitroaniline" : "2-Nitroaniline",
    "3-Nitroaniline" : "3-Nitroaniline",
    "4-Nitroaniline" : "4-Nitroaniline",
    "Nitrobenzene" : "Nitrobenzene",
    "2-Nitrophenol" : "2-Nitrophenol",
    "4-Nitrophenol" : "4-Nitrophenol",
    "N-Nitrosodiphenylamine" : "N-Nitrosodiphenylamine",
    "N-Nitrosodi-n-propylamine" : "N-Nitrosodi-n-propylamine",
    "Pentachlorophenol" : "Pentachlorophenol",
    "Phenanthrene" : "Phenanthrene",
    "Phenol" : "Phenol",
    "Pyrene" : "Pyrene",
    "Pyridine" : "Pyridine",
    "124-Trichlorobenzene" : "124-Trichlorobenzene",
    "245-Trichlorophenol" : "245-Trichlorophenol",
    "246-Trichlorophenol" : "246-Trichlorophenol",
    "1-Methylnaphthalene" : "1-Methylnaphthalene",
    "Other SVOCs" : "Other SVOCs",

    #Pesticides/PCBs
   "Aldrin" : "Aldrin",
   "Aldrin Dry" : "Aldrin Dry",
   "a-BHC" : "a-BHC",
   "a-BHC Dry" : "a-BHC Dry",
   "b-BHC" : "b-BHC",
   "b-BHC Dry" : "b-BHC Dry",
   "d-BHC" : "d-BHC",
   "d-BHC Dry" : "d-BHC Dry",
   "g-BHC" : "g-BHC",
   "g-BHC Dry" : "g-BHC Dry",
   "Chlordane (Technical)" : "Chlordane",
   "Chlordane (Technical) Dry" : "Chlordane Dry",
   "a-Chlordane" : "a-Chlordane",
   "a-Chlordane Dry" : "a-Chlordane Dry",
   "g-Chlordane" : "g-Chlordane",
   "g-Chlordane Dry" : "g-Chlordane Dry",
   "p,p-DDD" : "p,p-DDD",
   "p,p-DDD Dry" : "p,p-DDD Dry",
   "p,p-DDE" : "p,p-DDE",
   "p,p-DDE Dry" : "p,p-DDE Dry",
   "p,p-DDT" : "p,p-DDT",
   "p,p-DDT Dry" : "p,p-DDT Dry",
   "Dieldrin" : "Dieldrin",
   "Dieldrin Dry" : "Dieldrin Dry",
   "Endosulfan I" : "Endosulfan I",
   "Endosulfan I Dry" : "Endosulfan I Dry",
   "Endosulfan II" : "Endosulfan II",
   "Endosulfan II Dry" : "Endosulfan II Dry",
   "Endosulfan sulfate" : "Endosulfan sulfate",
   "Endosulfan sulfate Dry" : "Endosulfan sulfate Dry",
   "Endrin" : "Endrin",
   "Endrin Dry" : "Endrin Dry",
   "Endrin aldehyde" : "Endrin aldehyde",
   "Endrin aldehyde Dry" : "Endrin aldehyde Dry",
   "Endrin ketone" : "Endrin ketone",
   "Endrin ketone Dry" : "Endrin ketone Dry",
   "Heptachlor" : "Heptachlor",
   "Heptachlor Dry" : "Heptachlor Dry",
   "Heptachlor epoxide" : "Heptachlor epoxide",
   "Heptachlor epoxide Dry" : "Heptachlor epoxide Dry",
   "Hexachlorobenzene" : "Hexachlorobenzene",
   "Hexachlorobenzene Dry" : "Hexachlorobenzene Dry",
   "Hexachlorocyclopentadiene" : "Hexachlorocyclopentadiene",
   "Hexachlorocyclopentadiene Dry" : "Hexachlorocyclopentadiene Dry",
   "Methoxychlor" : "Methoxychlor",
   "Methoxychlor Dry" : "Methoxychlor Dry",
   "Toxaphene" : "Toxaphene",
   "Toxaphene Dry" : "Toxaphene Dry",
   "Other Pesticides" : "Other Pesticides",
   "Other Pesticides Dry" : "Other Pesticides Dry",
   "Aroclor1016" : "Aroclor1016",
   "Aroclor1016 Dry" : "Aroclor1016 Dry",
   "Aroclor1221" : "Aroclor1221",
   "Aroclor1221 Dry" : "Aroclor1221 Dry",
   "Aroclor1232" : "Aroclor1232",
   "Aroclor1232 Dry" : "Aroclor1232 Dry",
   "Aroclor1242" : "Aroclor1242",
   "Aroclor1242 Dry" : "Aroclor1242 Dry",
   "Aroclor1248" : "Aroclor1248",
   "Aroclor1248 Dry" : "Aroclor1248 Dry",
   "Aroclor1254" : "Aroclor1254",
   "Aroclor1254 Dry" : "Aroclor1254 Dry",
   "Aroclor1260" : "Aroclor1260",
   "Aroclor1260 Dry" : "Aroclor1260 Dry",
   "PCBs, total" : "PCBs, total",
   "PCBs, total Dry" : "PCBs, total Dry",

    #Inorganics
    "Reactive Cyanide": "Reactive CN-",
    "Total Cyanide": "CN-",
    "Ignitability_screen": "RCI",
    "Reactive Sulfide": "Sulfides",
    "Total Suspended Solids": "TSS",
    "Chloride": "Cl",
    "Dissolved Sulfide": "Diss. Sulfides",
    "Corrosivity" : "Corrosivity",
    "% Moisture" : "% Moisture",
    "Sulfides" : "Sulfides",
    "Ignitability" : "Ignitability",
    "Methane" : "Methane",
    

    #PFAS
    "10:2 FTS" :"10:2 FTS",
    "11ClPF3OUdS":"11ClPF3OUdS",
    "3:3 FTCA":"3:3 FTCA",
    "4:2 FTS":"4:2 FTS",
    "5:3 FTCA":"5:3 FTCA",
    "6:2 FTS":"6:2 FTS",
    "7:3 FTCA":"7:3 FTCA",
    "9ClPF3ONS":"9ClPF3ONS",
    "ADONA":"ADONA",
    "EtFOSA":"EtFOSA",
    "EtFOSE":"EtFOSE",
    "HFPO-DA":"HFPO-DA",
    "MeFOSA":"MeFOSA",
    "MeFOSE":"MeFOSE",
    "NEtFOSAA":"NEtFOSAA",
    "NFDHA":"NFDHA",
    "NMeFOSAA":"NMeFOSAA",
    "PFBA":"PFBA",
    "PFBS":"PFBS",
    "PFDA":"PFDA",
    "PFDoA":"PFDoA",
    "PFDS":"PFDS",
    "PFEESA":"PFEESA",
    "PFHpA":"PFHpA",
    "PFHpS":"PFHpS",
    "PFHxA":"PFHxA",
    "PFHxDA":"PFHxDA",
    "PFHxS":"PFHxS",
    "PFMBA":"PFMBA",
    "PFMPA":"PFMPA",
    "PFNA":"PFNA",
    "PFNS":"PFNS",
    "PFOA":"PFOA",
    "PFODA":"PFODA",
    "PFOSA":"PFOSA",
    "PFPeA":"PFPeA",
    "PFPeS":"PFPeS",
    "PFTeDA":"PFTeDA",
    "PFTrDA":"PFTrDA",
    "PFUnA":"PFUnA",
    "8:2 FTS":"8:2 FTS",
    "PFOS":"PFOS",
}

T1_list_order = [
    "Anchor",
    "Sample ID",
    "Sample Date",
    "TPHs-G/BTEX/MTBE",
    "TPHs-D/MO",
    "Carbonyls",
    "VOCs",
    "SVOCs",
    "Pesticides and PCBs",
    "PFAS",
    "Title-22 Metals",
    "WET Sb",
    "WET As",
    "TCLP As",
    "WET Ba",
    "TCLP Ba",
    "WET Be",
    "WET Cd",
    "TCLP Cd",
    "WET Cr",
    "TCLP Cr",
    "Cr +6",
    "WET Cr+6",
    "WET Co",
    "WET Cu",
    "WET Pb",
    "TCLP Pb",
    "WET Hg",
    "TCLP Hg",
    "WET Mo",
    "WET Ni",
    "WET Se",
    "TCLP Se",
    "WET Ag",
    "TCLP Ag",
    "WET Tl",
    "WET V",
    "WET Zn",
    "CN-",
    "Reactive CN-",
    "CH4",
    "pH",
    "RCI",
    "Corrosivity"
    "Sulfides",
    "TSS",
    "COD",
    "TRPH",
    "Salinity",
    "Cl",
    "Diss. Sulfides",
    "Asbestos",
]


metals_order = [
    "Sb",
    "WET Sb",
    "As",
    "WET As",
    "TCLP As",
    "Ba",
    "WET Ba",
    "TCLP Ba",
    "Be",
    "WET Be",
    "Cd",
    "WET Cd",
    "TCLP Cd",
    "Cr",
    "WET Cr",
    "TCLP Cr",
    "Cr +6",
    "WET Cr+6",
    "Co",
    "WET Co",
    "Cu",
    "WET Cu",
    "Pb",
    "WET Pb",
    "TCLP Pb",
    "Hg",
    "WET Hg",
    "TCLP Hg",
    "Mo",
    "WET Mo",
    "Ni",
    "WET Ni",
    "Se",
    "WET Se",
    "TCLP Se",
    "Ag",
    "WET Ag",
    "TCLP Ag",
    "Tl",
    "WET Tl",
    "V",
    "WET V",
    "Zn",
    "WET Zn",
    "Asbestos",
]

TPH_BTEX_order = [
    "TPHs-G",
    "TPHs-D",
    "TPHs-MO",
    "Benzene",
    "Ethyl Benzene",
    "Ethylbenzene"
    "Toluene",
    "TRPH",
    "Xylenes",
    "MTBE",
    "Carbonyls",
]

VOCs_order = [
    "Acetone",
    "tert-Amyl methyl ether (TAME)",
    "Benzene",
    "Bromobenzene",
    "Bromochloromethane",
    "Bromodichloromethane",
    "Bromoform",
    "Bromomethane",
    "2-Butanone (MEK)",
    "t-Butyl alcohol (TBA)",
    "n-Butyl benzene",
    "sec-Butyl benzene",
    "tert-Butyl benzene",
    "Carbon Disulfide",
    "Carbon Tetrachloride",
    "Chlorobenzene",
    "Chloroethane",
    "Chloroform",
    "Chloromethane",
    "2-Chlorotoluene",
    "4-Chlorotoluene",
    "Dibromochloromethane",
    "1,2-Dibromo-3-chloropropane",
    "1,2-Dibromoethane (EDB)",
    "Dibromomethane",
    "Dichlorodifluoromethane",
    "1,2-Dichlorobenzene",
    "1,3-Dichlorobenzene",
    "1,4-Dichlorobenzene",
    "Dibromofluoromethane",
    "1,1-Dichloroethane",
    "1,2-Dichloroethane (1,2-DCA)",
    "1,1-Dichloroethene",
    "cis-1,2-Dichloroethene",
    "trans-1,2-Dichloroethene",
    "1,2-Dichloropropane",
    "1,3-Dichloropropane",
    "1,3-Dichloropropene, Total",
    "2,2-Dichloropropane",
    "1,1-Dichloropropene",
    "cis-1,3-Dichloropropene",
    "trans-1,3-Dichloropropene",
    "Diisopropyl ether (DIPE)",
    "Ethylbenzene",
    "Ethyl tert-butyl ether (ETBE)",
    "Freon 113",
    "Hexachlorobutadiene",
    "Hexachloroethane",
    "2-Hexanone",
    "Isopropylbenzene",
    "4-Isopropyl toluene",
    "Methyl-t-butyl ether (MTBE)",
    "Methylene chloride",
    "4-Methyl-2-pentanone (MIBK)",
    "Naphthalene",
    "n-Propyl benzene",
    "Styrene",
    "1,1,1,2-Tetrachloroethane",
    "1,1,2,2-Tetrachloroethane",
    "Tetrachloroethene",
    "Toluene",
    "1,2,3-Trichlorobenzene",
    "1,2,4-Trichlorobenzene",
    "1,1,1-Trichloroethane",
    "1,1,2-Trichloroethane",
    "Trichloroethene",
    "Trichlorofluoromethane",
    "1,2,3-Trichloropropane",
    "1,2,4-Trimethylbenzene",
    "1,3,5-Trimethylbenzene",
    "Vinyl Chloride",
    "Total Xylenes",
]

SVOCs_order = [
    "Acenaphthene",
    "Acenaphthylene",
    "Acetochlor",
    "Anthracene",
    "Benzidine",
    "Benzo (a) anthracene",
    "Benzo (b) fluoranthene",
    "Benzo (k) fluoranthene",
    "Benzo (g,h,i) perylene",
    "Benzo (a) pyrene",
    "Benzyl Alcohol",
    "1,1-Biphenyl",
    "Bis (2-ethylhexyl) Adipate",
    "Bis (2-chloroethoxy) Methane",
    "Bis (2-chloroethyl) Ether",
    "Bis (2-chloroisopropyl) Ether",
    "Bis (2-ethylhexyl) Phthalate",
    "4-Bromophenyl Phenyl Ether",
    "Butylbenzyl Phthalate",
    "4-Chloroaniline",
    "4-Chloro-3-methylphenol",
    "2-Chloronaphthalene",
    "2-Chlorophenol",
    "4-Chlorophenyl Phenyl Ether",
    "Chrysene",
    "Dibenzo (a,h) anthracene",
    "Dibenzofuran",
    "Di-n-butyl Phthalate",
    "1,2-Dichlorobenzene",
    "1,3-Dichlorobenzene",
    "1,4-Dichlorobenzene",
    "3,3-Dichlorobenzidine",
    "2,4-Dichlorophenol",
    "Diethyl Phthalate",
    "2,4-Dimethylphenol",
    "Dimethyl Phthalate",
    "4,6-Dinitro-2-methylphenol",
    "2,4-Dinitrophenol",
    "2,4-Dinitrotoluene",
    "2,6-Dinitrotoluene",
    "Di-n-octyl Phthalate",
    "1,2-Diphenylhydrazine",
    "Fluoranthene",
    "Fluorene",
    "Hexachlorobenzene",
    "Hexachlorobutadiene",
    "Hexachlorocyclopentadiene",
    "Hexachloroethane",
    "Indeno (1,2,3-cd) pyrene",
    "Isophorone",
    "1-Methylnaphthalene",
    "2-Methylnaphthalene",
    "2-Methylphenol (o-Cresol)",
    "3 & 4-Methylphenol (m,p-Cresol)",
    "Naphthalene",
    "2-Nitroaniline",
    "3-Nitroaniline",
    "4-Nitroaniline",
    "Nitrobenzene",
    "2-Nitrophenol",
    "4-Nitrophenol",
    "N-Nitrosodiphenylamine",
    "N-Nitrosodi-n-propylamine",
    "Pentachlorophenol",
    "Phenanthrene",
    "Phenol",
    "Pyrene",
    "Pyridine",
    "1,2,4-Trichlorobenzene",
    "2,4,5-Trichlorophenol",
    "2,4,6-Trichlorophenol",
]


pest_PCBs_order = [
    "Aldrin",
    "Aldrin Dry",
    "a-BHC",
    "a-BHC Dry",
    "b-BHC",
    "b-BHC Dry",
    "d-BHC",
    "d-BHC Dry",
    "g-BHC",
    "g-BHC Dry",
    "Chlordane (Technical)",
    "Chlordane (Technical) Dry",
    "a-Chlordane",
    "a-Chlordane Dry",
    "g-Chlordane",
    "g-Chlordane Dry",
    "p,p-DDD",
    "p,p-DDD Dry",
    "p,p-DDE",
    "p,p-DDE Dry",
    "p,p-DDT",
    "p,p-DDT Dry",
    "Dieldrin",
    "Dieldrin Dry",
    "Endosulfan I",
    "Endosulfan I Dry",
    "Endosulfan II",
    "Endosulfan II Dry",
    "Endosulfan sulfate",
    "Endosulfan sulfate Dry",
    "Endrin",
    "Endrin Dry",
    "Endrin aldehyde",
    "Endrin aldehyde Dry",
    "Endrin ketone",
    "Endrin ketone Dry",
    "Heptachlor",
    "Heptachlor Dry",
    "Heptachlor epoxide",
    "Heptachlor epoxide Dry",
    "Hexachlorobenzene",
    "Hexachlorobenzene Dry",
    "Hexachlorocyclopentadiene",
    "Hexachlorocyclopentadiene Dry",
    "Methoxychlor",
    "Methoxychlor Dry",
    "Toxaphene",
    "Toxaphene Dry",
    "Other Pesticides",
    "Other Pesticides Dry",
    "Aroclor1016",
    "Aroclor1016 Dry",
    "Aroclor1221",
    "Aroclor1221 Dry",
    "Aroclor1232",
    "Aroclor1232 Dry",
    "Aroclor1242",
    "Aroclor1242 Dry",
    "Aroclor1248",
    "Aroclor1248 Dry",
    "Aroclor1254",
    "Aroclor1254 Dry",
    "Aroclor1260",
    "Aroclor1260 Dry",
    "PCBs, total",
    "PCBs, total Dry",
]

other_inorg_order = [
    "CN-",
    "Reactive CN-",
    "CH4",
    "pH",
    "RCI",
    "Corrositity",
    "Ignitability",
    "Sulfides",
    "TSS",
    "COD",
    "Salinity",
    "Cl",
    "Diss. Sulfides",
    "% Moisture"
    "Methane",
]
 
PFAS_order = [
    "10:2 FTS",
    "11ClPF3OUdS",
    "3:3 FTCA",
    "4:2 FTS",
    "5:3 FTCA",
    "6:2 FTS",
    "7:3 FTCA",
    "9ClPF3ONS",
    "ADONA",
    "EtFOSA",
    "EtFOSE",
    "HFPO-DA",
    "MeFOSA",
    "MeFOSE",
    "NEtFOSAA",
    "NFDHA",
    "NMeFOSAA",
    "PFBA",
    "PFBS",
    "PFDA",
    "PFDoA",
    "PFDS",
    "PFEESA",
    "PFHpA",
    "PFHpS",
    "PFHxA",
    "PFHxDA",
    "PFHxS",
    "PFMBA",
    "PFMPA",
    "PFNA",
    "PFNS",
    "PFOA",
    "PFODA",
    "PFOSA",
    "PFPeA",
    "PFPeS",
    "PFTeDA",
    "PFTrDA",
    "PFUnA",
    "8:2 FTS",
    "PFOS",
    ]

soil_vapor_order = [
    "Acetone", "Acrolein", "Acrylonitrile",
]


output_table_col_order = {
    "Table 1 List": T1_list_order,
    "Soil Metals": metals_order,
    "Soil TPHs, BTEX & Organic": TPH_BTEX_order,
    "VOCs": VOCs_order,
    "SVOCs": SVOCs_order,
    "Soil Pesticides and PCBs": pest_PCBs_order,
    "PFAS": PFAS_order,
    "Other Inorganic": other_inorg_order,
    "GW Metals": metals_order,
    "GW TPHs, BTEX & Organic": TPH_BTEX_order,
    "GW VOCs": VOCs_order,
    "GW SVOCs": SVOCs_order,
    "GW Pesticides and PCBs": pest_PCBs_order,
    "GW PFAS": PFAS_order,
    "GW Other Inorganics": other_inorg_order,
    "Soil Vapor VOCs": soil_vapor_order,
}


numbered_output_tables = {
    "Table 1 List": 1,
    "Table 1 List Notes": 2,
    "Soil Metals": 3,
    "Soil Metals Notes": 4,
    "Soil TPHs, BTEX & Organic": 5,
    "Soil TPHs, BTEX & Organic Notes": 6,
    "VOCs": 7,
    "VOCs Notes": 8,
    "SVOCs": 9,
    "SVOCs Notes": 10,
    "Soil Pesticides and PCBs": 11,
    "Soil Pesticides and PCBs Notes": 12,
    "PFAS":13,
    "PFAS Notes": 14,
    "Other Inorganic": 15,
    "Other Inorganic Notes": 16,
    "GW TPHs, BTEX & Organic": 17,
    "GW TPHs, BTEX & Organic Notes": 18,
    "GW VOCs": 19,
    "GW VOCs Notes": 20,
    "GW SVOCs": 21,
    "GW SVOCs Notes": 22,
    "GW Pesticides and PCBs": 23,
    "GW Pesticides and PCBs Notes": 24,
    "GW Metals": 25,
    "GW Metals Notes": 26,
    "GW Other Inorganics": 27,
    "GW Other Inorganics Notes": 28,
    "Soil Vapor VOCs":29,
    "Soil Vapor VOCs Notes":30,
}

analytes_to_drop = [
    "Reactive Cyanide",
    "m,p-Xylene",
    "o-Xylene",
    "% Moisture",
]

list_of_analyte_groups = [
    "Soil Metals",
    "Soil TPHs, BTEX & Organic",
    "VOCs",
    "SVOCs",
    "Soil Pesticides and PCBs",
    "PFAS",
    "Other Inorganic",
    "GW Metals",
    "GW TPHs, BTEX & Organic",
    "GW VOCs",
    "GW SVOCs",
    "GW Pesticides and PCBs",
    "GW Other Inorganics",
    "Soil Vapor VOCs",
]

list_of_footnotes_groups = [
    "Table 1 List Notes",
    "Soil Metals Notes",
    "Soil TPHs, BTEX & Organic Notes",
    "VOCs Notes",
    "SVOCs Notes",
    "Soil Pesticides and PCBs Notes",
    "PFAS Notes"
    "Other Inorganic Notes",
    "GW Metals Notes",
    "GW TPHs, BTEX & Organic Notes",
    "GW VOCs Notes",
    "GW SVOCs Notes",
    "GW Pesticides and PCBs Notes",
    "GW Other Inorganics Notes",
    "Soil Vapor VOCs Notes",
]


regulatory_category_dict = {
    "Risk Regulatory and Reference Criteria": [
        "USEPA RSL Residential",
        "USEPA RSL Industrial",
        "ESL - Tier 1",
        "ESL - Residential",
        "ESL - Commerical",
        "DTSLs SLs - Residential",
        "DTSCs SLs - Commerical",
        "ESL - Construction Workers",
        "California OSHA Permissible Exposure Limits",
        "Concentration in California Benchmark Soil",
    ],
    "Hazardous Waste Criteria": [
        "TTLC", "STLCx10", "STLC", "TCLPx20", "TCLP"
    ],
    "Recycling Facility Acceptance Criteria": [
        "Baylands Soil Processing",
        "Lennar Urban - Candlestick Point Redevelopment",
    ],
    "Range of Potential Background Concentration": [
        "Shaklette and Boerngen",
        "LBNL",
        "Bradford et al.",
    ],
    "Wastewater Discharge Criteria": [
        "SFPUC Batch Discharge Criteria"
    ],
    "Risk Regulatory and Reference Criteria (GW)": [
    "ESL - Tier 1 (GW)"
    ],
    "Risk Regulatory and Reference Criteria (SV)": [
        "Subslab / Soil Gas ESL - Tier 1","Subslab / Soil Gas ESL - Residential",
        "Subslab / Soil Gas ESL - Commercial","Indoor Air ESL - Tier 1",
        "Indoor Air ESL - Residential","Indoor Air ESL - Commercial",
        "Air DTSCs SLs - Residential","Air DTSC SLs - Commercial"
    ]

}

tables_for_nd_drop = [
    "VOCs",
    "SVOCs",
    "Soil Pesticides and PCBs",
    "PFAS",
    "GW Pesticides and PCBs",
    "GW VOCs",
    "GW SVOCs",
    "Soil Vapor VOCs",
]

gw_criteria = [
    "SFPUC Batch Discharge Criteria",
    "ESL - Tier 1 (GW)",
]

sv_criteria = [
    "Subslab / Soil Gas ESL - Tier 1","Subslab / Soil Gas ESL - Residential","Subslab / Soil Gas ESL - Commercial",
    "Indoor Air ESL - Tier 1","Indoor Air ESL - Residential","Indoor Air ESL - Commercial",
    "Air DTSCs SLs - Residential","Air DTSC SLs - Commercial",
]

health_crit_list = ["USEPA RSL Residential","USEPA RSL Industrial","ESL - Tier 1","ESL - Commerical",
    "ESL - Construction Workers","California OSHA Permissible Exposure Limits","ESL - Residential",
    "DTSLs SLs - Residential","DTSCs SLs - Commerical","Concentration in California Benchmark Soil",
    "ESL - Tier 1 (GW)","Subslab / Soil Gas ESL - Tier 1","Subslab / Soil Gas ESL - Residential",
    "Subslab / Soil Gas ESL - Commercial","Indoor Air ESL - Tier 1","Indoor Air ESL - Residential",
    "Indoor Air ESL - Commercial","Air DTSCs SLs - Residential","Air DTSC SLs - Commercial",]

# dictionary with table headings for each analyte group
analytegroup_table_headings = {
    "Table 1 List": "List of Chemical Analyses on Soil and Groundwater Samples",
    "Soil Metals": "Results of Title 22 Metals and Asbestos Analyses on Soil Samples",
    "Soil TPHs, BTEX & Organic": "Results of Total Petroleum Hydrocarbons, BTEX, and MTBE Analyses on Soil Samples",
    "VOCs": "Results of VOCs Analyses on Soil Samples",
    "SVOCs": "Results of SVOCs Analyses on Soil Samples",
    "Soil Pesticides and PCBs": "Results of Pesticides and PCBs Analyses on Soil Samples",
    "PFAS" : "Results of Per- and Ployfluoroalkyl Substances on Soil Samples",
    "Other Inorganic": "Results of pH, Methane and RCI Analyses on Soil Samples",
    "GW TPHs, BTEX & Organic": "Results of Total Petroleum Hydrocarbons, BTEX, and MTBE Analyses on Groundwater Samples",
    "GW VOCs": "Results of VOCs Analyses on Groundwater Samples",
    "GW SVOCs": "Results of SVOCs Analyses on Groundwater Samples",
    "GW Pesticides and PCBs": "Results of Pesticides and PCBs Analyses on Groundwater Samples",
    "GW Metals": "Results of Title 22 Metals Analyses on Groundwater Samples",
    "GW Other Inorganics": "Results of Other Inorganics Analyses on Groundwater Samples",
    "Soil Vapor VOCs":"Results of Soil Vapor VOCs Analyses on Soil Vapor Samples",
}

extra_header_list = ["Soil Metals", "Soil TPHs, BTEX & Organic"]


soil_tables_list = [
    "Soil Metals",
    "Soil TPHs, BTEX & Organic",
    "VOCs",
    "SVOCs",
    "Soil Pesticides and PCBs",
    "PFAS",
    "Other Inorganic",
]

gw_tables_list = [
    "GW Metals",
    "GW TPHs, BTEX & Organic",
    "GW VOCs",
    "GW SVOCs",
    "GW Pesticides and PCBs",
    "GW Other Inorganics",
]

sv_tables_list = [
    'Soil Vapor VOCs'
]


